### ISSUE TITLE
Initial number of columns incorrect when in landscape

### ISSUE THREAD

**Issue by youjinp** [paololeonardi/WaterfallGrid#13]
**Summary**
When the initial device orientation is landscape, the number of columns displayed is incorrect. The correct number of columns is displayed only after rotating to portrait and landscape again.

**Expected**
![Screen Shot 2019-11-20 at 12 31 22 PM](https://user-images.githubusercontent.com/15708500/69195852-bac72c00-0b91-11ea-9969-5e0f24669672.png)

**Actual**
![Screen Shot 2019-11-20 at 12 31 08 PM](https://user-images.githubusercontent.com/15708500/69195876-c155a380-0b91-11ea-9ba6-fd98ee176807.png)

**Env**
Xcode 11.2, iOS 13.2, Swift 5

**Comment by paololeonardi** [comment]
@youjinp thanks for raising and fixing the issue.
