### ISSUE TITLE
Grid that fits contents?

### ISSUE THREAD

**Issue by nrbrook** [paololeonardi/WaterfallGrid#22]
I want to use WaterfallGrid to contain some buttons which are laid out in a grid depending on the size available. WaterfallGrid is in a `VStack` with a `List` and some other views. I want the grid to just fit the buttons, so to fit the content as tightly as possible, and disable scrolling. Is this possible?
<img width="372" alt="Screenshot 2020-01-27 at 09 48 53" src="https://user-images.githubusercontent.com/1141167/73164849-a3a13f00-40ea-11ea-9f71-9bc10b8d39b7.png">

**Comment by paololeonardi** [comment]
Hi @nrbrook, sorry the late reply!
I'm afraid is not possible to use the grid this way.
If the elements don't fit inside the grid frame, the grid becomes scrollable and the property cannot be disabled.
