### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mkalayci35** [paololeonardi/WaterfallGrid#24]
<img width="856" alt="Screen Shot 2020-02-13 at 17 00 04" src="https://user-images.githubusercontent.com/38668796/74442282-48a96f00-4e82-11ea-862d-ffa7027a96d2.png">
precondition failure: invalid input index: 2

**Comment by mkalayci35** [comment]
<img width="875" alt="Screen Shot 2020-02-13 at 17 00 30" src="https://user-images.githubusercontent.com/38668796/74442319-5828b800-4e82-11ea-8492-10399f65f3c1.png">

**Comment by paololeonardi** [comment]
Could you please provide some more details on the crash?
I wasn't able to reproduce it in the sample app so it could be something to do with the specific way you are using the grid.

Thanks

**Comment by mkalayci35** [comment]
tabbar Create 2 menus. put too many pictures in one scrollview. and go down. Scroll down to another menu and come back again. He will give an error because he did not take where he was staying

**Comment by wlwg** [comment]
I'm having exactly the same issue. I have a tab view that has two tab item, within each having a waterfallGrid. Switching between these two tabs will trigger that error. Anyone has a solution?
