### ISSUE TITLE
WaterfallGrid don't showing in Navigation View

### ISSUE THREAD

**Issue by tuandapen** [paololeonardi/WaterfallGrid#25]
Example code

NavigationView {
            WaterfallGrid((0..<10), id: \.self) { index in
                Image(systemName: "photo")
                    .resizable()
                    .aspectRatio(contentMode: .fit)
            }
        }

**Comment by paololeonardi** [comment]
Hi @tuandapen 
I've just tried to replicate the issue but I correctly see the grid inside the NavigationView:

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            WaterfallGrid((0..<10), id: \.self) { index in
                Image(systemName: "photo")
                    .resizable()
                    .aspectRatio(contentMode: .fit)
            }.navigationBarTitle("NavigationView")
        }
    }
}
```


![Screenshot 2020-03-23 at 18 08 53](https://user-images.githubusercontent.com/4065078/77348964-3993c780-6d32-11ea-8014-d7ec7faaf679.png)
**Xcode**: 11.3.1
**iOS Simulator**: 13.2
