### ISSUE TITLE
Position Issue

### ISSUE THREAD

**Issue by LiYanan2004** [paololeonardi/WaterfallGrid#26]
I have created this view, and I noticed when I clicked on the rectangle which have more than 1 item in it, it will go into navigationLink View and then when I back to this main View, the first rectangle goes to the bottom. I have made sure that this is not my code issue. Can you help me? 

<img width="309" alt="截屏2020-03-17下午9 00 20" src="https://user-images.githubusercontent.com/37542129/76858430-63f90700-6892-11ea-8599-d8ee9f96c221.png">

ThankYou very much.

**Comment by paololeonardi** [comment]
Hi @LiYanan2004,
I tried to replicate a similar layout with `navigationLink` actions.
I didn't notice anything odd happening with the positions of the items.

![navigationLink](https://user-images.githubusercontent.com/4065078/77356498-52a27580-6d3e-11ea-9e97-a59d942cbaaf.gif)
(https://gist.github.com/paololeonardi/c226351b1144bd991fbbc47e732e5acb)

By chance, are you updating the collection of data used to render the grid when the main view appears? If you try to inspect the grid in Xcode with the "Debug View Hierarchy" tool,  do you see any hidden view on the top left corner?
