### ISSUE TITLE
How to disable scrolling?

### ISSUE THREAD

**Issue by bobshoemaker** [paololeonardi/WaterfallGrid#30]
Hi there! 

I was wondering if there is any way to disable the scrolling option and just have the stack show up? I'm trying to create a 2 by 2 grid. 

WaterfallGrid((0..<4), id: \.self) { index in
                Rectangle()
                    .foregroundColor(Color("primary"))
                    .cornerRadius(8)
                    .frame(height: 125)
            }
            .gridStyle(
                columns: 2,
                spacing: 24,
                padding: EdgeInsets(top: 20, leading: 30, bottom: 30, trailing: 30)
            )

Thank you!

**Comment by paololeonardi** [comment]
Hi @bobshoemaker,

Sorry, the grid doesn't currently support the option to disable the scrolling.

However if the layout you are trying to achieve is that simple with regular elements, I suggest you to build it yourself:

i.e.
```swift
import SwiftUI

struct MyGrid: View {
    private let spacing: CGFloat = 24
    private let padding = EdgeInsets(top: 20, leading: 30, bottom: 30, trailing: 30)

    var body: some View {
        VStack(spacing: self.spacing) {
            ForEach(0..<2) { _ in
                HStack(spacing: self.spacing) {
                    MyRectangle()
                    MyRectangle()
                }
            }
        }.padding(self.padding)
    }
}

struct MyRectangle: View {
    var body: some View {
        Rectangle()
            .foregroundColor(.red)
            .cornerRadius(8)
            .frame(height: 125)
    }
}
```

![Screenshot 2020-04-14 at 16 08 45](https://user-images.githubusercontent.com/4065078/79241392-e9a8ac00-7e6a-11ea-83e6-d67d3af762cc.png)

**Comment by bobshoemaker** [comment]
Hi @paololeonardi, 

Understood - thanks for the tip!
