### ISSUE TITLE
right to left grid

### ISSUE THREAD

**Issue by eskanndar** [paololeonardi/WaterfallGrid#34]
I need it to be right to left grid. is there any possibility to do that?

**Comment by paololeonardi** [comment]
You could force the grid environment to have an RTL layout direction:

```swift
WaterfallGrid(rectangles) { rectangle in
  RectangleView(rectangle: rectangle)
}
.environment(\.layoutDirection, .rightToLeft)
```

Is it what you want?

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-15 at 15 25 08](https://user-images.githubusercontent.com/4065078/84669920-5698fa80-af1d-11ea-9bdf-86fdaef4f2de.png)

**Comment by eskanndar** [comment]
Yes, thank you. great job.
