### ISSUE TITLE
passing array of URLs to image grid 

### ISSUE THREAD

**Issue by ClaesClaes** [paololeonardi/WaterfallGrid#37]
Hi, your WaterfallGrid seems very nice and could fit in may App. However I wonder if you could giving me some pointers or direct help on how I can adapt your image grid example so that I can pass an array of URLs (URLs of jpg's in my Apps document directory) instead of using Assets.xcassets?
Regards,
Claes

**Comment by paololeonardi** [comment]
Hi @ClaesClaes, thanks!

There is no built-in SwiftUI method to create `Image` from an URL.
You could do that indirectly with `init(uiImage: UIImage)`. 
(https://developer.apple.com/documentation/swiftui/image)

Some useful resources:
https://www.google.com/search?as_q=image+url+swiftui
https://github.com/search?q=image+swiftui

**Comment by ClaesClaes** [comment]
Hi Paolo, many thanks for your help. After reading your linked resources and some tinkering I solved it. I enclose my
solution in case it can help someone else with a similar need. Suggestions for improvements are more than welcome.
 
1) first I added a FileManager extension that list and returns an array of all available .jpg files in the document directory like this:

```Swift
/*----------------------------------------------------------------------------------------
Filemanager extension for scanning and returning .jpg filenames in the document directory
Usage: let fileList = FileManager.findAllJpgFiles()
----------------------------------------------------------------------------------------*/
extension FileManager {
    class func directoryUrl() -> URL? {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        return paths.first
    }
    class func findAllJpgFiles() -> [URL]? {
        if let documentsUrl = FileManager.directoryUrl() {
            do {
                let directoryContents = try FileManager.default.contentsOfDirectory(at: documentsUrl, includingPropertiesForKeys: nil)
                return directoryContents.filter{ $0.pathExtension == "jpg" }
            } catch {
                return nil
            }
        }
        return nil
    }
}

```
2) the I added a helper to the ImagesGrid.swift that load one image at a time using the results from the FileManage.findAllJpgFile() extension

```Swift
private func loadImage(fileURL: URL) -> UIImage? {
        do {
            let imageData = try Data(contentsOf: fileURL)
            return UIImage(data: imageData)
        } catch {
            print("Error loading image : \(error)")
            return nil
        }
    }
```
3) finally I adapted the ImagesGrid.swift from your example like this:

```Swift
var body: some View {
        return WaterfallGrid((FileManager.findAllJpgFiles()!), id: \.self) { image in
            Image(uiImage: self.loadImage(fileURL: image)!)
                .resizable()
                .aspectRatio(contentMode: .fit)
                .onTapGesture {
                   // add action for tap gesture
            }
         }
        .gridStyle(
            columnsInPortrait: 2,
            columnsInLandscape: 4,
            spacing: 1,
            padding: .init(top: 1, leading: 1, bottom: 1, trailing: 1),
            animation: .default
        )
    } 
```

**Comment by paololeonardi** [comment]
@ClaesClaes thank you!
This would definitely help others with a similar need.
