### ISSUE TITLE
how to disable scrolling

### ISSUE THREAD

**Issue by UnrealCherry** [paololeonardi/WaterfallGrid#40]

**Comment by adel-bassiony** [comment]
I think you should remove the `ScrollView`, so we can add it inside a `ScrollView` with other content.
or you can add an option to disable the `ScrollView`

**Comment by UnrealCherry** [comment]
> I think you should remove the `ScrollView`, so we can add it inside a `ScrollView` with other content.
> or you can add an option to disable the `ScrollView`

  WaterfallGrid  can't  pull up refresh and pull down loadding . 
  i must use  ScrollView  outside here
