### ISSUE TITLE
Deleting items, with animation

### ISSUE THREAD

**Issue by andrewlilley-ux** [paololeonardi/WaterfallGrid#43]
Are there plans to allow for deleting items, with animation?

**Comment by paololeonardi** [comment]
With grid style, you can pass the animation to use when data change.
The animation applies to the deleted items as well.
Does this answer your question?

```swift
WaterfallGrid(rectangles, content: RectangleView.init)
.gridStyle(
  animation: .easeInOut(duration: 0.5)
)
```

<img src="https://paololeonardi.github.io/waterfallgrid/resources/issues/delete-animation.gif" alt="Delete Animation"/>

**Comment by andrewlilley-ux** [comment]
Yeah, thanks.
