### ISSUE TITLE
iOS 14

### ISSUE THREAD

**Issue by wanmeixx** [paololeonardi/WaterfallGrid#47]
Not show in NavigationView
Not support lazyload

**Comment by ablyes** [comment]
You are right 
The actual result leads to an app that is still running but with an empty grid. 
iOs 14 will be released today ! 
Should we expect a quick fix or is it too complex to fix ?

**Comment by ablyes** [comment]
No answer :( I guess i have to use another lib or implement it by myself.

**Comment by Turacbey** [comment]
List is now showed on iOS 14 sometimes :/

**Comment by paulo2703** [comment]
Does it work now?

**Comment by Turacbey** [comment]
It has not updated for IOS 14. It doesn't work

> Does it work now?

**Comment by paololeonardi** [comment]
Hey, could you please provide few more details or an example code?
