### ISSUE TITLE
Layout issue in simulators

### ISSUE THREAD

**Issue by ay42** [paololeonardi/WaterfallGrid#8]
Hi just wanted to mention that there is a layout issue on simulators (iPhone 11 Pro). Awesome grid btw.
![Simulator Screen Shot - iPhone 11 Pro - 2019-11-06 at 12 19 06](https://user-images.githubusercontent.com/2933241/68334932-5e8fe280-0090-11ea-8ecb-e935705f1ea3.png)

**Comment by paololeonardi** [comment]
Hi Alex, thanks, so is yours!

About the bug, you are right. Looks like there are layout issues on iOS 13.2 and not just iPhone 11 Pro. On iOS 13.1, where it was mainly tested, works fine.
I'll investigate it further.

Thank you!
